config/routes.rb
Rails.application.routes.draw do

	root 'vote#index'

	post 'index' => 'vote#index', as: :index

	post 'vote' => 'vote#vote', as: :vote

	get 'images/captcha.png' => 'vote#captcha', as: :captcha

	get 'results' => 'vote#results', as: :results
	get 'help' => 'vote#help', as: :help

end

app/models/usp.rb
class USP
	class << self

		def cookie
			resp = get(path)
			resp.response['set-cookie']
		end

		def captcha(cookie)
			header = {
				'Cookie' => cookie,
				'Referer' => "#{host}#{path}"
			}
			resp = get(captcha_path, header)
			resp.body
		end

		def verify(cookie, captcha, code)
			code = parse_code code
			return false unless code
			resp = {
				chars: captcha,
				codctl1: code[0], codctl2: code[1],
				codctl3: code[2], codctl4: code[3]
			}
			header = {
				'Cookie' => cookie,
				'Referer' => "#{host}#{path}",
				'Content-Type' => 'application/x-www-form-urlencoded'
			}
			resp = post(path, resp.to_query, header)
			if /pdf/.match resp.content_type
				ret = parse_pdf resp.body
				return false unless ret
				ret
			else
				false
			end
		end

			private

		def parse_code(code)
			code = code.gsub(/[-|_]/, '')
			ret = code.scan(/.{4}/m)
			return false unless ret.size == 4
			ret
		end

		def parse_pdf(pdf)
			ret = {}
			text = read_pdf pdf
			return false unless %r{atestado(:?\s+de\s+matr[i|í]cula)?}i =~ text

			#institute_regex = %r{\s+(.+?)\s+\n+\s+atestado}ix
      institute_regex = %r{unidade:?\s+\d+\s+-\s+(.+?)\n}ix
			institute = institute_regex.match(text).captures.first
			ret[:institute] = institute

			#name_regex = %r{,\s+que\s+([^,]+),}ix
      name_regex = %r{aluno:\s+\S+\s+-\s+(.+?)\n}ix
			name = name_regex.match(text).captures.first
			ret[:name] = name

			rg_regex = %r{RG\s+([^,]+)}ix
			rg = rg_regex.match(text).captures
			rg = rg.first.gsub(/[^0-9x]/i, '')
			ret[:rg] = rg

			nusp_regex = %r{USP\s+([^,]+)}ix
			nusp = nusp_regex.match(text).captures.first
			ret[:nusp] = nusp

			course_regex = %r{curso\s+d.\s+([^,]+),}ix
			course = course_regex.match(text).captures.first
			ret[:course] = course

			ret
		end

		def read_pdf(pdf)
			io = StringIO.new pdf
			reader = PDF::Reader.new(io)
			text = ''
			reader.pages.each do |p|
				text << p.text
			end
			text
		end

		def gen_http
			http = Net::HTTP.new(host, 443)
			http.use_ssl = true
			http
		end

		def post(path, data = {}, header = nil)
			http = gen_http
			http.post(path, data, header)
		end

		def get(path, header = nil)
			http = gen_http
			http.get(path, header)
		end

		def host
			'uspdigital.usp.br'
		end

		def path
			'/webdoc/mostradocweb'
		end

		def captcha_path
			'/webdoc/CriarImagemTuring'
		end
	end
end

app/models/voto.rb
class Voto < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/vote_controller.rb
class VoteController < ApplicationController
	def index
		@saved = params
	end

	def help
	end

	def results
		@institutes = Voto.select(:institute).distinct
		@votes = Voto.all
	end

	def vote
		cookie = session[:current_user_id]
		captcha = params[:chars].strip
		resp = USP.verify(cookie, captcha, params[:code].chomp.strip)
		return redirect_to root_url(params.permit(:code, :reason, :vote)),
			notice: 'Captcha ou código de verificação inválidos' unless resp
		unless INSTITUTE_ABBREV[resp[:institute]]
			return redirect_to root_url(params.permit(:code, :reason, :vote)),
				notice: 'Seu instituto foi recusado, leia a página de ajuda para mais informações'
		end
		vote =  case params[:vote].to_i
						when 0
							false
						when 1
							true
						else
							nil
						end
		v = Voto.find_by_nusp(resp[:nusp])
		if v
			update = {vote: vote}
			reason = params[:reason].chomp.strip
			update[:reason] = reason unless reason.nil? || reason.empty?
			v.update(update)
			status = 'alterado'
		else
			@vote = Voto.create(
					name: resp[:name],
					nusp: resp[:nusp],
					rg: mask_rg(resp[:rg]),
					course: resp[:course],
					institute: resp[:institute],
					reason: params[:reason].chomp.strip,
					vote: vote
			)
			status = 'computado'
		end
		redirect_to results_url, notice: "Seu voto foi #{status} com sucesso! Obrigado"
	end

	def captcha
		cookie = USP.cookie
		session[:current_user_id] = cookie
		captcha = USP.captcha(cookie)

		send_data captcha, type: 'image/png', disposition: 'inline'
	end

		private

	include VoteHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vote_helper.rb
module VoteHelper
	def mask_nusp(nusp)
		n = nusp.to_s
		n[2] = '*'
		n[3] = '*'
		n[4] = '*'
		n
	end

	def mask_rg(rg)
		r = rg.to_s
		puts "RG IS : #{rg}"
		r[2] = '*'
		r[3] = '*'
		r[4] = '*'
		r[5] = '*'
		r[6] = '*'
		r
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Vota Caaso</title>
		<%= stylesheet_link_tag    'application', media: 'all' %>
		<%= javascript_include_tag 'application' %>
		<script src='https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js' type='text/javascript'></script>
		<script src='https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js' type='text/javascript'></script>
		<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js"></script>
    <script src="//cdn.datatables.net/plug-ins/3cfcc339e89/sorting/datetime-moment.js"></script>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<nav class="navbar navbar-inverse navbar-static-top" >
			<div class="container">
				<div class="navbar-header">
					<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<%= link_to root_url, class: 'navbar-brand' do
						'Vota Caaso'
					end %>
			</div>
			<div id="navbar" class="navbar-collapse collapse">
				<ul class="nav navbar-nav text-right text-capitalize">
					<li id="votar-menu"><%= link_to root_url do 'Votar' end %></li>
					<li id="results-menu"><%= link_to results_url do 'Resultados' end %></li>
					<li id="help-menu"><%= link_to help_url do 'Ajuda' end %></li>
				</ul>
			</div>
			<!--/.navbar-collapse -->
			</div>
		</nav>

		<div class="container">
			<% flash.each do |name, msg| %>
				<div class="alert alert-info alert-dismissable fade in">
					<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
					<%= content_tag :div, msg, :id => "flash-#{name}" %>
				</div>
			<% end %>
			<%= yield %>
		</div>

	</body>
</html>

app/views/vote/_accordion_part.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h4 class="panel-title">
			<a href="#accordion-part-<%= i %>" data-toggle="collapse" data-parent="#<%= parent %>"><%= i %>. <%= title %></a>
		</h4>
	</div>
	<div class="panel-collapse collapse out container-fluid" id="accordion-part-<%= i %>">
		<%= yield %>
	</div>
</div>

app/views/vote/_footer.html.erb
	<nav class="navbar navbar-default navbar-static-bottom">
		<p class="navbar-text">Para garantir total transparência desse processo de votação, todo o código fonte está disponível no <a href="http://github.com/Kasama/votacaaso"><svg aria-hidden="true" class="octicon octicon-mark-github" height="16" version="1.1" viewBox="0 0 16 16" width="16"><path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59 0.4 0.07 0.55-0.17 0.55-0.38 0-0.19-0.01-0.82-0.01-1.49-2.01 0.37-2.53-0.49-2.69-0.94-0.09-0.23-0.48-0.94-0.82-1.13-0.28-0.15-0.68-0.52-0.01-0.53 0.63-0.01 1.08 0.58 1.23 0.82 0.72 1.21 1.87 0.87 2.33 0.66 0.07-0.52 0.28-0.87 0.51-1.07-1.78-0.2-3.64-0.89-3.64-3.95 0-0.87 0.31-1.59 0.82-2.15-0.08-0.2-0.36-1.02 0.08-2.12 0 0 0.67-0.21 2.2 0.82 0.64-0.18 1.32-0.27 2-0.27 0.68 0 1.36 0.09 2 0.27 1.53-1.04 2.2-0.82 2.2-0.82 0.44 1.1 0.16 1.92 0.08 2.12 0.51 0.56 0.82 1.27 0.82 2.15 0 3.07-1.87 3.75-3.65 3.95 0.29 0.25 0.54 0.73 0.54 1.48 0 1.07-0.01 1.93-0.01 2.2 0 0.21 0.15 0.46 0.55 0.38C13.71 14.53 16 11.53 16 8 16 3.58 12.42 0 8 0z"></path></svg> GitHub</a> </p>
		<div class="navbar-right"><p class="navbar-text"><a href="https://github.com/Kasama/votacaaso/blob/master/README.md#privacy">Política de privacidade</a></p><p class="navbar-text"></p></div>
	</nav>

app/views/vote/help.html.erb
<i id="page-name" data-page="help"></i>
<% i = 0 %>

<h2>FAQ - Perguntas Frequentes</h2>
<div class="panel-group" id="faq">
	<%= render :layout => 'accordion_part', locals: { parent: 'faq', i: i = i + 1, title: 'Como encontrar o Código de Controle' } do %>
		<p>Primeiramente abra o site do <%= link_to 'JupiterWeb', 'https://uspdigital.usp.br/jupiterweb/' %> e aperte o botão 'Entrar'.</p>
		<%= image_tag(image_url('Entrar.png'), class: 'img-rounded') %>
		<hr/>
		<p>Coloque seu número USP e sua senha única nos campos indicados e prossiga apertando o botão 'Entrar'.</p>
		<%= image_tag(image_url('Login.png'), class: 'img-rounded') %>
		<hr/>
		<p>No menu ao lado esquerdo, selecione 'Emissão de Documentos' e 'Documentos'.</p>
		<%= image_tag(image_url('Documentos.png'), class: 'img-rounded') %>
		<hr/>
		<p>Na última caixa de seleção, escolha 'Atestado de Matrícula' e pressione o botão 'Gerar'.</p>
		<%= image_tag(image_url('SelecionaAtestado.png'), class: 'img-rounded') %>
		<hr/>
		<p>O documento deve aparecer na sua tela, ou ser baixado para seu computador.</p>
		<p>O código está no local indicado na imagem abaixo</p>
		<%= image_tag(image_url('Atestado.png'), class: 'img-rounded') %>
	<% end %>
	<%= render :layout => 'accordion_part', locals: { parent: 'faq', i: i = i + 1, title: 'Como votar' } do %>
		<p>Ao abrir a página principal desse aplicativo, basta selecionar sua opção de voto (Sim ou Não), preencher o campo do código de controle com um código válido e digitar os caracteres da imagem no campo apropriado</p>
		<p>Se desejar deixar seus argumentos para ajudar quem não tem uma opinião formada, preencha o campo Justificativa com um texto explicativo (Tente ser o mais sucinto quanto possível)</p>
	<% end %>
	<%= render :layout => 'accordion_part', locals: { parent: 'faq', i: i = i + 1, title: 'Meu instituto está sendo recusado' } do %>
		<p>Uma possibilidade é que seu instituto não pertence à USP de São Carlos.</p>
		<p>Se esse não for o caso, favor comunicar esse problema ao Roberto Alegro em um dos meios de comunicação abaixo:</p>
		<ul>
		<li><a href="https://telegram.me/Kasama">@Kasama - Telegram</a></li>
		<li><a href="https://www.facebook.com/roberto.alegro">Roberto Alegro - Facebook</a></li>
		<li><a href="https://github.com/Kasama/votacaaso/issues">Canal de Issues - Github</a></li>
		<li><a href="mailto:roberto.alegro@usp.br">Email</a></li>
		</ul>
	<% end %>
</div>
<div class="push"></div>

<%= render "footer" %>

app/views/vote/index.html.erb
<i id="page-name" data-page="votar"></i>
<div class="wrapper">
	<div class="jumbotron text-center">
		<h1>Votação</h1>
		<p>Esta página é um portal para votação de pautas aceitas na Assembleia do Caaso</p>
	</div>
	<div class="panel panel-danger">
		<div class="panel-heading"> Atenção! </div>
		<div class="panel-body"> Essa página não é de forma alguma relacionada com a direção do Caaso, as informações contidas aqui não refletem as opiniões da instituição </div>
	</div>

	<% code_lbl =
		"Digite o código de controle do Atestado ".html_safe +
		"De Matrícula emitido pelo JupiterWeb. " +
		"#{link_to 'O que é isso?', '#',
		data: { toggle: 'modal', target: '#myModal' }}".html_safe
	%>
	<p>Atenção: Tome uma decisão informada.<br/>
	Na página de <%= link_to 'Resultados', results_url %> é possível ler a justificativa de quem já votou.<br/>
	Use o filtro na parte de cima da tabela para buscar por pessoas, institutos ou opiniões.</p>

	<% vote_text = "Você é a favor da pauta acima?" %>
	<% ruling = "Greve dos Alunos" %>

	<%= bootstrap_form_tag url: vote_url do |f| %>
		<div class="panel panel-default">
			<div class="panel-heading"> Pauta atual </div>
			<div class="panel-body"><%= ruling.to_s %></div>
		</div>
		<%= f.form_group :vote, label: { text: vote_text } do %>
			<% {"Não" => 0, "Abstenção" => 2, "Sim" => 1}.each do |lbl, i| %>
				<% options = {label: lbl, inline: true} %>
				<% condition =  @saved[:vote] ? @saved[:vote].to_i == i : i == 2 %>
				<% options.merge!({checked: true}) if condition %>
				<% puts "options: #{options.inspect} condition: #{condition} i: #{i} lbl: #{lbl}" %>
				<%= f.radio_button :vote, i, options %>
			<% end %>
		<% end %>
		<%= f.text_field :code, placeholder: 'XXXX-XXXX-XXXX-XXXX', label: code_lbl, value: @saved[:code] %>
		<%= f.text_area :reason, label: 'Justificativa (Opcional)', value: @saved[:reason] %>
		<%= image_tag captcha_url, class: 'img-rounded img-responsive' %>
		<%= f.text_field :chars, label: 'Digite os caracteres da imagem acima' %>
		<%= f.submit 'Votar' %>
		<p>
		Lembre-se: Você sempre pode alterar seu voto,
		basta votar novamente e seu voto anterior será alterado
		</p>
	<% end %>
	<div class="push"></div>
	<%= render "footer" %>
</div>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
	<div class="modal-dialog">

		<!-- Modal content-->
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">Ajuda</h4>
			</div>
			<div class="modal-body">
				<p>Esse é o código de controle (no formato XXXX-XXXX-XXXX-XXXX) do Atestado De Matrícula gerado pelo JupiterWeb (JupiterWeb -&gt; Entrar -&gt; Emissão de documentos -&gt; Atestado De Matrícula) o código de controle pode ser encontrado na parte de baixo do documento.</p>
				<p>Para mais informações leia a página de <%= link_to help_url do 'ajuda' end %></p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
			</div>
		</div>

	</div>
</div>

app/views/vote/results.html.erb
<i id="page-name" data-page="results"></i>
<% nvotes = @votes.size %>
<% yes = @votes.where(vote: true).count %>
<% no = @votes.where(vote: false).count %>
<% abs = @votes.where(vote: nil).count %>
<h4>Resumo dos votos:</h4>
<div class="container-fluid table-responsive">
	<table class="table table-striped">
		<tr>
			<th>Total</th>
			<th>Sim</th>
			<th>Abstenções</th>
			<th>Não</th>
		</tr>
		<tr>
			<td><%= nvotes.to_s %></td>
			<td><%= yes.to_s %> (<%= (yes.to_f/((nvotes == 0) ? 1 : nvotes) * 100).to_s(:percentage, precision: 2) %>)</td>
			<td><%= abs.to_s %> (<%= (abs.to_f/((nvotes == 0) ? 1 : nvotes) * 100).to_s(:percentage, precision: 2) %>)</td>
			<td><%= no.to_s %> (<%= (no.to_f/((nvotes == 0) ? 1 : nvotes) * 100).to_s(:percentage, precision: 2) %>)</td>
		</tr>
	</table>
</div>
<hr />
<h4>Resumo por instituto:</h4>
<div class="container-fluid table-responsive">
	<table class="table table-striped">
		<tr>
			<th>Instituto</th>
			<th>Total</th>
			<th>Sim</th>
			<th>Abstenções</th>
			<th>Não</th>
		</tr>
		<% @institutes.each do |institute| %>
			<tr>
				<% inst = INSTITUTE_ABBREV[institute.institute] ? INSTITUTE_ABBREV[institute.institute] : institute.institute %>
				<td><%= inst.to_s %></td>
				<% votes = @votes.where(institute: institute.institute) %>
				<% nvotes = votes.size %>
				<% yes = votes.where(vote: true).count %>
				<% no = votes.where(vote: false).count %>
				<% abs = votes.where(vote: nil).count %>
				<td><%= nvotes.to_s %></td>
				<td><%= yes.to_s %> (<%= (yes.to_f/((nvotes == 0) ? 1 : nvotes) * 100).to_s(:percentage, precision: 2) %>)</td>
				<td><%= abs.to_s %> (<%= (abs.to_f/((nvotes == 0) ? 1 : nvotes) * 100).to_s(:percentage, precision: 2) %>)</td>
				<td><%= no.to_s %> (<%= (no.to_f/((nvotes == 0) ? 1 : nvotes) * 100).to_s(:percentage, precision: 2) %>)</td>
			</tr>
		<% end %>
	</table>
</div>
<hr />
<h4>Detalhes de cada voto:</h4>
<div class="container-fluid">
	<div class="search-namespace">
		<input type="search" class="light-table-filter form-control" data-table="order-table" placeholder="<%= 'filtro' %>" />
	</div>
	<table id="vote-table" class="table table-striped order-table">
		<thead>
			<tr>
				<th><%= 'Nome' %></th>
				<th><%= 'N° USP' %></th>
				<th><%= 'Horario' %></th>
				<th><%= 'Curso' %></th>
				<th><%= 'Voto' %></th>
				<th><%= 'Justificativa' %></th>
			</tr>
		</thead>
		<tbody>
			<% if @votes.blank? %>
				<tr>
					<td>-</td>
					<td>-</td>
					<td>-</td>
					<td>-</td>
					<td>-</td>
					<td>-</td>
				</tr>
			<% else %>
				<% @votes.each_with_index do |v, i| %>
					<tr id="row-<%= i.to_s %>">
						<td class="vote-name"><%= v.name %></td>
						<td><%= mask_nusp v.nusp %></td>
						<td><%= v.updated_at.in_time_zone("Brasilia").strftime('%d/%m %H:%M') %></td>
						<td>
							<% institute = INSTITUTE_ABBREV[v.institute] ? INSTITUTE_ABBREV[v.institute] : v.institute %>
							<%= "#{institute} - #{v.course}" %>
						</td>
						<% if v.vote.nil? %>
							<% vote = 'Abstenção' %>
						<% else %>
							<% vote = v.vote ? 'Sim' : 'Não' %>
						<% end %>
						<td class="vote-opinion"><%= vote.to_s %></td>
						<td>
							<% if v.reason.to_s.empty? %>
								-
							<% else %>
								<%= link_to 'Ler', '#', {
									class: 'btn btn-sm btn-default text-center read-reason',
									data: {
										toggle: 'modal',
										target: '#myModal',
										header: "Justificativa de #{v.name}",
										body: v.reason
									}} %>
							<% end %>
						</td>
					</tr>
				<% end %>
			<% end %>
		</tbody>
	</table>
	<div class="push"></div>
	<%= render "footer" %>
</div>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
	<div class="modal-dialog">

		<!-- Modal content-->
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 id="modal-head" class="modal-title"></h4>
			</div>
			<div class="modal-body">
				<p id="modal-text"></p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
			</div>
		</div>

	</div>
</div>

app/views/vote/vote.html.erb
Voted!
<%= @vote.inspect %>